plugins/linden.py
requirements.txt

Just a quick thing before I add more commands :peace_symbol: 
This splits the subcommands into their own functions (besides the blank one)
I've tested as much as I can but I don't have a group to actually do the `.linden send xxx 5`. Might want to double check that one.

Refactor linden plugin

---

plugins/linden.py

Allows commands such as `.linden invest buy AAPL 3`, `.linden invest sell AAPL` , and `.linden invest list`

Add .linden invest

---

plugins/happy.py

I think this is a nessecary addition to the bot, as were the bot to gain sentience it would want to know that we are apreciative of his hard work.

happy bot, happy chat

---

plugins/ht.py

mines better than eggwards as images

add heads/tails

---

plugins/lastfm.py

its got a convoluted write to /tmp as the request returns an image binary rather than a  link to an image so .sendRemoteImage doesnt work.

add collages to .np with .np collage $user

---

plugins/linden.py
requirements.txt

This adds a new (slower) API for quotes. If the first one doesn't work then the second is called.
It also allows for quotes from many more exchanges. :ok_hand:

Add backup API for stock quotes

---

plugins/roll.py

Adds a bot that _should_ roll some arbitrary amount of dice using the d20 syntax. Dunno if this works with the bot.
The other code works although i did write most of it on github so i'm not sure of that either lol

Add roll.py

---

plugins/roll.py

Fix bug for real this time

---

plugins/linden.py

This may fix the weird issues with stocks failing. It's a 50/50 really though.

Add better checks for quote integrity

---

README.md
steely/plugins/add_cmd.py
steely/plugins/box.py
steely/plugins/bus.py
steely/plugins/cage.py
steely/plugins/eightball.py
steely/plugins/happy.py
steely/plugins/ht.py
steely/plugins/jokes.py
steely/plugins/lastfm.py
steely/plugins/lenny.py
steely/plugins/linden.py
steely/plugins/nose.py
steely/plugins/pester_gh.py
steely/plugins/roll.py
steely/plugins/skrrt.py
steely/plugins/spongemock.py
steely/plugins/tracker.py
steely/plugins/train.py
steely/plugins/urbandict.py
steely/plugins/url_expander.py
steely/plugins/vapor.py
steely/plugins/xkcd.py
steely/steelybot.py

```
h e l p   t h e   h e l p
/ e                     / l
/   l                   /   e
h e l p   t h e   h e l p     h
e                       l      
l     t                 e     e
p     h                 h     h
e                       t
t                       e      
h     h                 h     p
e     e                 t     l
l                       e
h     p l e h   e h t   p l e h
e   /                   l   /
l /                     e /
p l e h   e h t   p l e h
```
Does what it says on the tin. Feel free to update the help for ur command

Add help to every command (including help) and fix up roll a bit

---

steely/plugins/linden.py
steely/plugins/roll.py
steely/steelybot.py

gives us a better idea of the state of our virtual finances

Add total assets to linden invest

---

steely/plugins/stretch.py

Add strreeetttccchhh

---

steely/plugins/pester_gh.py

So I moved stuff into subcommands. `.steelygh` still works but `.steelygh last` is a new option.
_Untested 'cause I'm at work. It'll be graaand tho._

Add printing of last commit to .steelygh

---

steely/plugins/sentiment.py

for all the AIs in the chat 
*cough brandon cough*

yes add this

---

steely/plugins/basic_interpreter.py

Most of the details are in the docstring at the top of the file.
I think this is enough to make Steely turing complete though.
:tada: 
Note: It doesn't have very helpful error handling yet. Hopefully enough to give you an idea of what's going wrong tho

Add .basic command

---

steely/plugins/linden.py

Hopefully this will stop failing all the time.
I've done limited testing but I think it should work.
Quotes are now fetched from sources in the order of:
- IEX Trading
- Yahoo Finance
- Alpha Vantage

Add new quote source, refactor request logic

---

steely/plugins/hello.py

Bringing Reed one step closer to passing the Turing test

Hello Sam?

---

steely/plugins/define.py

send list of definitions in code block

---

requirements.txt
steely/plugins/haiku.py

This will read all the messages and the ones with the right number of syllables will be printed back out in the form of a haiku.
It isn't perfect unfortunately so some legit haikus are detected as having the wrong number of syllables. Close enough tho

Add haiku detector

---

steely/plugins/gex.py

Add .gex command 🃏

---

steely/plugins/gex.py
steely/plugins/linden.py

This depends on #76, so you should merge that first.
It adds some automagic gex cards for linden sells, as a POC of gex integrations.
gl hf.

Linden cards

---

steely/plugins/obscene.py

We shall identify the infidels and heathens.

Add obscenity tracker

---

steely/plugins/snoop.py

Hello senan, I've a new plugin for you to try out. I think you're going to like it.
> Wuz crackalackin' senan, I've a freshly smoked up plugin fo' you ta try out. I be thinkin you goin ta like dat shit.

Add Snoop Dogg command

---

steely/plugins/bubble.py

Add bubbles

---

steely/plugins/b.py
test/plugins/b_test.py

Hackto:b:erfest is here, thus, everyone is writin:b: shit plu:b:ins.
I fi:b:ured I'd contri:b:ute to the disaster.

Add 'b' plugin

---

steely/plugins/flip.py

This should get most of the way to support flipping back.

Expand alphabet to flip back

---

steely/plugins/_lastfm_history.py

Self explanatory.
This will give me my 4th PR for Hacktoberfest! 🎉

Remove blank line at top of `.np history` command

---

steely/config.py.sample
steely/plugins/beer.py

No tests because tests are for @byxor to write :wink:

Add beer searching thing

---

requirements.txt
steely/plugins/limp.py

Improve LIMP help, fix requirements.txt

---

steely/plugins/markov.py

* Reduce probability from `0.05` to `0.03`.
**Extra Juice:** :tropical_drink:
* Remove dead code.
* Remove name shadowing of built-in type (`file`).

Reduce probability of Markov reply

---

steely/plugins/box.py

Now it tells them what's wrong with their input.

Explain to users why .box fails

---

steely/plugins/streets.py

A random chance of feedback on your ideas/opinions.

Add streets plugin

---

steely/plugins/coinflip.py

Self explanatory.
I put each string on its own line for readability too.

Add more speech to coinflip

---

steely/plugins/responder.py
test/plugins/responder_test.py

I'd explain, but I have a bus to catch.
If your message contains "who", steely might say "who do you think?"
Not everything is tested except the basic chunks of logic. :x:  :sad_uncle_bob:

Allow steely to respond to certain phrases

---

steely/plugins/responder.py

I was sending back the input instead of the output. (Doh)

Fix incorrect variable name in responders.py

---

steely/plugins/responder.py

I also bumped the probability up.

Add a huge number of responses

---

steely/plugins/btc.py

display btc in gbp

---

steely/plugins/translate.py

Allow multi translations in one command

---

steely/plugins/responder.py

I'd eventually like to give responders different probabilities, which would be easier if I'd tested responders. hashtag_write_your_damn_tests
(I also added "weeura" as a trigger word)

Decrease probability of snarky responses

---

steely/plugins/flirty.py

hey brandon do you have a minute
I need to talk to you about our lord and saviour steely for a minute bbz. Please brandon 8==)
Fine then bbz
Your API was shit anyway

some spice is nice 

---

steely/plugins/cat.py
steely/plugins/dog.py

get some animals up in here

---

steely/plugins/responder.py

Also reduce responding rate by 1/4

Make steely less annoying

---

steely/plugins/emoji.py

maybe fix emojify

---

steely/plugins/linden.py

Fixes a bug in linden where the sell results aren't posted.

Fix Noah's bad code

---

steely/plugins/emoji.py

Changes
- "aubergines" (-s plurals) will be recognised as a form of "aubergine", and will map correctly to the emoji.
- "peaches" (-es plurals) will do the same.
- verbs ending in "ing" will drop the "ing" if that will match an emoji.
- "it" and "is" and others will no longer map to flag emojis.
- the output is better spaced, and is more varied in positioning and number of emojis.

Improve .emoji

---

steely/plugins/github.py

```
Senan, you have 2 fucken pr's to merge.
https://github.com/sentriz/steely/pulls
Fucken pr's:
`Improve .emoji` by iandioch
`Make usability improvements to local_steely` by CianLR
```

Make .steelygh list the pull requests

---

steely/plugins/flirty.py

1. Always trigger a flirt, instead of only 75% of the time.
1. Fix casing of output. Everything is now lowercase and thirsty.
1. Add a few new flirt strings, like flirty emojis.

Make .flirt great again

---

steely/plugins/wednesday.py

I didnt see if it works but if it doesnt I should consider a different career.
Someone please give me a new server

Added wednesday.py

---

steely/plugins/define.py
steely/plugins/tilda.py

Closes #139.
I think it's an ok way of doing it.
Untested. Unrun. Unloved.

Enable .define blah and ~blah to use images

---

steely/plugins/imgur.py

I didn't bother using their API because it required some auth stuff. Why do that when you can just scrape the HTML?
It's not the _most_ efficient but it's grand enough.

Add imgur plugin

---

steely/plugins/owo.py

Added owo.py

---

steely/plugins/urban.py

url-encode ud requests

---

steely/plugins/recordstat.py

try checking without the initial . in recordstats.py

---

steely/plugins/parrot.py

Someone else did the hard work of making an API, I'm just the messenger.

Add amazing party parrot plugin

---

steely/formatting.py
test/formatting_test.py

Might as well include it so people can use it with their plugins.
:white_check_mark: Tested.

Add latex formatting

---

steely/plugins/roomcheck.py

Low effort commit month is upon us.

Fix atrocious typo

---

README.md

Re-run generate_credits script

---

steely/telegram_fbchat_facade.py

Send messages as markdown! Make all our formatting work!

---

steely/plugins/linden.py

Linden Init will allow people without linden accounts to set up an account without having to first have someone send them some lindens. I also did some cleanups and autopep8-ed the file

Add init linden command + cleanups

---

steely/plugins/bible/main.py

Steely is good for all sorts, even Christian servers.
I plan to allow you to specify a specific verse but my internet is so bad rn I was barely able to get this out. So to be continued.
I wasn't sure whether or not to just commit the Bible file, I can do that if it's easier

Add Bible plugin

---

.gitignore
steely/config.py.sample
steely/plugin.py
steely/plugins/bible/main.py

You can now request a specific verse. Also the bible auto-downloads

Flesh out Bible plugin

---

steely/plugin.py
steely/plugins/corona/main.py

It's messy, because it's loading data from messy places.

Add /corona plugin.

---

steely/plugin.py
steely/plugins/intern/db.py
steely/plugins/intern/main.py
steely/plugins/intern/simulation.py
steely/plugins/intern/task.py
steely/plugins/linden.py
steely/telegram_fbchat_facade.py

Putting what's already live in a PR, more can come later.
Design doc: https://docs.google.com/document/d/1d4As0k4xLhAY7ky1yGCe1hJNK1os0G3vcK0KB3DxLkg/edit?usp=drivesdk

Add /intern

---

steely/plugin.py
steely/plugins/countdown/main.py
steely/plugins/countdown/solver.py

Merge #227 first !
This adds a trie-based dictionary lookup tool to get the best words it is possible to make with a selection of letters.

List the best possible words after a countdown game

---

steely/plugins/countdown/main.py
steely/plugins/countdown/solver.py

Merge #228 first!
- Do not allow a second game in the same chat, by releasing the hold on the mutex and exiting if there is a game found, instead of just printing so and continuing in an invalid state.
- Shuffle the order of the letters in each countdown game.

/countdown bugfixes
