cpssd-students/steely

steelybot.py
For some reason my phone corrects .linden to .Linden
This is easier than figuring out how to add something to my dictionary.
=> Make plugin commands case insensitive

.gitignore, Makefile, README.md, requirements.txt, steely/plugins/url_expander.py, test/plugins/url_expander_test.py
:white_check_mark: Contains tests.
* Adds plugin to expand short URLs.
* Adds Makefile so `make test` can be used (handy).
* Adds `nose` as a requirement.
* Adds emacs backup files to `.gitignore`
* I haven't tested any bot-related code.
* Tests currently invoke `expand(url)` function that makes HTTP requests.
* They will fail offline.
* I chose not to mock and HTTP-related code because I don't want to enforce the idea that the plugin-code should expand URLs via HTTP.
=> Add url expansion plugin

requirements.txt, steely/plugins/limp_evaluation.py
Allows users to evaluate [limp](https://www.github.com/byxor/limp). 👌 
```                                       
UncleBob: ".limp (+ 2 3)"
Chat_Bot: "5"
```                                    
```
UncleBob: ".limp (// 100 (- 5 2))"
Chat_Bot: "33"
```
:warning: Plugin comes with no tests, limp is already tested as its own python package.
* Remember to **re-install pip dependencies** after merging.
=> Add plugin to evaluate limp

steely/plugins/limp_evaluation.py
1. If the return value of `limp.evaluate` is 0, it will now send properly.
2. Error messages now have their types displayed when sent.
1. `send` is now an available function for steely. It will send a message to the chat. _(Bear in mind that LIMP doesn't have strings yet, so we can only send ints and floats)_
* I haven't ran/tested anything that has been added here.
* I've never used f-strings before, so it's possible that I've made a mistake.
=> Add multiple improvements to limp_evaluation plugin

steely/plugins/gex.py
Adds:
- Limits to card ID lengths when printing some stuff to stop it looking daft.
- A list of card owners to `.gex inspect`.
- `.gex decks`, which lists users in order of the number of cards they have.
- `.gex stats`, which gives some statistics on the state of the gex kingdom.
- A cleaner help thing, and autocorrect of subcommands, because I need a new hobby.
=> Add .gex stats

steely/plugins/github.py
People are using `.steelygh` a lot nowadays (given the sudden influx of shitty hacktoberfest plugins).
Sometimes I want a quick way to check the PRs, and the addition of this link will make that easier.
=> Add PR url to steelygh command

steely/formatting.py, steely/plugins/_lastfm_helpers.py, steely/plugins/_lastfm_history.py, steely/plugins/_lastfm_list.py, steely/plugins/_lastfm_np.py, steely/plugins/_lastfm_top.py, steely/plugins/b.py, steely/plugins/box.py, steely/plugins/bus.py, steely/plugins/define.py, steely/plugins/eight.py, steely/plugins/gex.py, steely/plugins/goth.py, steely/plugins/help.py, steely/plugins/linden.py, steely/plugins/roll.py, steely/plugins/stats.py, steely/plugins/tracker.py, steely/plugins/train.py, test/formatting_test.py
`formatting.py` contains helpers that apply text formatting.
✅ `code_block`
✅ `bold`
✅ `italic`
✅ `strikethrough`
✅ `monospace`
It's tested.
I went through a bunch of plugins and changed the duplicate code to use these helpers.
I may have missed some things.
I tried very hard to keep the plugins working. If they had tests, it'd be easy to catch errors quickly.
From now on, please do all your formatting through this library. Replacing the duplication was slightly painful.
=> Add Facebook Formatting Helpers

steely/plugins/limp.py
Now you can't attempt to define the same thing twice and break the entire plugin.
=> Fix symbol redefinition errors for global definitions

steely/plugins/btc.py, test/plugins/btc_test.py
Now we get a nice little percentage that tells us how much bitcoin has gone up (or down) in value since the last time the command was run.
:moneybag: :chart_with_upwards_trend: :white_check_mark: 
---
**Notes:**
* I've added tests for the simple bits of logic I've added.
* I had to split up the `get_btc` function into smaller pieces; I relied on the rates rather than their string-formatted counterparts.
* The error messages that were returned from `get_btc` have changed to exceptions; this keeps the return type of the `get_bitcoin_rates` function consistent and makes it much easier to report errors to the user.
* I may have made a silly mistake. I'm not able to run most of this code. :warning:
=> Add percentage increase to bitcoin plugin

steely/plugins/basic_interpreter.py
10 LET R = 0
20 LET RESULT = 1
30 PRINTLN RESULT
Outputs: 0
*But not anymore* 👌
=> Fix bug where arg name is truncated in BASIC

steely/plugins/deepdream.py
People won't have to wait 30 seconds to find out if it's working anymore.
=> Add explanatory message for deepdream users

steely/local_steely.py, steely/utils.py
This adds a script to emulate messenger in order to test plugins locally.
So far fetchThreadMessages and sendMessage are the only operations supported but this should cover most plugins.
It has support for loading all the plugins but I recommend manually specifying the ones you want.
```
clr@clr-ThinkPad-T470:~/Desktop/steely/steely$ python3.6 local_steely.py -p mock.py b.py
>>> Hey babe
>>> .mock
hey bABe
>>> .b
hey 🅱️A🅱️e
```
=> Add initial version of local steely

steely/plugins/_haskell.sh, steely/plugins/_lastfm_collage.py, steely/plugins/_lastfm_np.py, steely/plugins/haskell.py, steely/plugins/lastfm.py
* Evaluates a haskell file.
* Shows compiler output.
* Long-running programs are killed (no infinite loops).
* FileSystem is protected from reads/writes.
* Network connections are currently allowed (afaik).
* Install `ghc` (haskell compiler).
* Install `firejail` (preferably from source) (sandboxing program).
* `ulimit -u 250` to prevent forkbombs.
Refrain from holding back the review because there's a setup process involved. There's no standard "setup script" kind of system yet, and I don't intend to implement one in this PR. I also don't intend to duplicate setup information.
```haskell
.haskell main = print (9 + 10)
```
```
Compiler Output:
[1 of 1] Compiling Main             ( temporary/code.hs, temporary/code.o )
Linking temporary/main ...
Program Output:
19
```
```haskell
.haskell …
```
=> Add (insanely improved) haskell plugin

steely/plugins/_gex_util.py, steely/plugins/linden.py, steely/plugins/markov.py, steely/steely_telegram.py, steely/telegram_fbchat_facade.py
Blurb:
/gex and /linden might even work now, idk; I think /linden just needs some initial user to trigger everything, and /linden just needs the database to populate with user_id -> name mappings (+ the search user by name func is required).
The markov plugin also has a small change here to suppress an error.
Some facebook-only stuff (eg. emoji) is removed.
Details:
Using "thread" to mean "channel"/"group chat"/etc.:
Everyone's favourite stock market gambling plugin is built around user_id <-> name stuff, so we require a way to do [user ID, user real name, thread] admin.
Telegram doesn't allow (right now) arbitrary querying of users by ID. They only allow querying a combo of (thread_id, user_id). Telegram also doesn't allow querying all users in a given thread. To support these functions, …
=> Telegram bug bash: add user handling so that /gex and /linden are less broken

README.md, steely/plugins/_gex_util.py, steely/plugins/_lastfm_milestone.py, steely/plugins/gex.py, steely/plugins/recordstat.py, steely/steely_telegram.py, steely/telegram_fbchat_facade.py
Fixes `/np milestone`, `/np collage`, `/np` (sometimes didn't work because markdown parsing failed, as the markdown parser is dumb and doesn't recognise URLs and the like)
Does some gex stuff
allows you to do `/np@steelybot` which is what Telegram sends by default if you hit the suggested command from the pop-up list after you start typing a command.
Adds TODO to fix `/stats`, which is just as good as an impl
=> Telegram bug bash: fix /np milestone, /np collage, /np[@steelybot]

steely/plugins/_lastfm_list.py
`/np list` was failing because the key `recenttracks` didn't exist in the response JSON. Adding `KeyError` to this `except` clause handles that.
`IndexError` must also be caught, in order to handle the case where `response.json()['recenttracks']['track']` doesn't have a 0'th element.
=> Fix /np list

steely/plugins/recordstat.py, steely/steely_telegram.py
`/stats` was previously broken on Telegram, as it turns out it was only recognising a valid command as being a message starting with `.`, but Telegram messages start with `/`. This PR fixes that so that /stats counts anything that looks like it might be a command. It's a bit overzealous (it'll count `...` and `~_~` as being commands too, IIUC), but better to overcount than undercount imo.
=> Fix /stats so that Telegram gets command counts

steely/plugins/xkcd.py, steely/steely_telegram.py
- Fix `/xkcd` so it works with telegram
- Do not try to trigger plugins for a text-less message, so that there aren't 10 errors printed any time someone posts an image.
=> Shush some errors & fix /xkcd

steely/plugin.py, steely/plugins/letterboxd/main.py, steely/steely_telegram.py
Closes #138.
Nothing was agreed in #138, so I wrote https://docs.google.com/document/d/17gS_hrBiXDyB4UCvKRlNv9JvBVzerFQVQIS5AQboM5Y/edit, and then decided myself on an approach. If you have some problem with it, merge this PR then submit a change later, otherwise this PR will sit in limbo forever...
Known problems:
- Helpstrings aren't added to the global helpstring directory (yet...)
- There's Undefined Behaviour if a plugin using the new style is defined in a file directly below `/plugins`. I think it'll work fine, I just didn't try it.
- Part 4 of the doc above isn't implemented, but is mostly tangential anyway.
- There's lots of functionality of /nw that is missing / could be improved.
- I'd like to wrap the whole (bot, author_id, message, thread_id, thread_type) shindig in some nicer …
=> Add new decorator-based plugin config system, and an example plugin using it: /nw

steely/steely_telegram.py
Old-style commands expect the `message` arg to not contain the command call that triggered them, so `/np iandioch` should just send with `message="iandioch"`. With changes in #216, this (accidentally) changed. It's because all the variables were all called `message` :angry: 
This PR fixes my oopsie woopsie.
=> Fix all plugins except /nw
